version: '3.3'

services:
  application:
    build: .
    ports:
      - 3000:3000
    links:
      - database
      - redis

  database:
    image: postgres:9.6
    restart: always
    ports:
      - 5432:5432
    volumes:
      - ./postgres/init:/docker-entrypoint-initdb.d
      - ./postgres/test:/test
    environment:
      POSTGRES_USER: "postgres"
      POSTGRES_PASSWORD: "password"
      POSTGRES_INITDB_ARGS: "--encoding=UTF-8"

  redis:
    image: redis:5-alpine
    ports:
      - 6379:6379
